LABEL_DISPLAY_VI = {
    "a": "a",
    "ai": "ai",
    "an": "ăn",
    "b": "b",
    "ban": "bạn",
    "bandem": "ban đêm",
    "baogio": "bao giờ",
    "bundau": "bún đậu",
    "buoichieu": "buổi chiều",
    "buoisang": "buổi sáng",
    "buoitrua": "buổi trưa",
    "c": "c",
    "cacban": "các bạn",
    "camon": "cảm ơn",
    "cangay": "cả ngày",
    "chungtoi": "chúng tôi",
    "d": "d",
    "dd": "đ",
    "e": "e",
    "homqua": "hôm qua",
    "khoe": "khỏe",
    "lucnao": "lúc nào",
    "may": "mấy",
    "muonkhong": "muốn không",
    "ngoi": "ngồi",
    "nha": "nhà",
    "odau": "ở đâu",
    "phaikhong": "phải không",
    "ten": "tên",
    "thich": "thích",
    "toi": "tôi",
    "tuoi": "tuổi",
    "v": "v",
    "xinchao": "xin chào",
    "xinloi": "xin lỗi",
    "y": "y",
}


def display_label(label: str) -> str:
    return LABEL_DISPLAY_VI.get(label.strip().lower(), label.strip())
